//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Libraries.ToolControls.PMSChart.Properties
{
	using System;

    
	/// <summary>
	///   一个强类型的资源类，用于查找本地化的字符串等。
	/// </summary>
	// 此类是由 StronglyTypedResourceBuilder
	// 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
	// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
	// (以 /str 作为命令选项)，或重新生成 VS 项目。
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute ()]
	internal class Resources
	{
        
		private static global::System.Resources.ResourceManager resourceMan;
        
		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute ("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources ()
		{
		}

		/// <summary>
		///   返回此类使用的缓存的 ResourceManager 实例。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute (global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals (resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager ("PMS.Libraries.ToolControls.PMSChart.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   使用此强类型资源类，为所有资源查找
		///   重写当前线程的 CurrentUICulture 属性。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute (global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap _00_05_ {
			get {
				object obj = ResourceManager.GetObject ("(00,05)", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap _00_12_ {
			get {
				object obj = ResourceManager.GetObject ("(00,12)", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap _01_00_ {
			get {
				object obj = ResourceManager.GetObject ("(01,00)", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap _02_00_ {
			get {
				object obj = ResourceManager.GetObject ("(02,00)", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap _12_01_ {
			get {
				object obj = ResourceManager.GetObject ("(12,01)", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap _13_01_ {
			get {
				object obj = ResourceManager.GetObject ("(13,01)", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap _18_39_ {
			get {
				object obj = ResourceManager.GetObject ("(18,39)", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap _40_37_ {
			get {
				object obj = ResourceManager.GetObject ("(40,37)", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap _41_22_ {
			get {
				object obj = ResourceManager.GetObject ("(41,22)", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap chart_type_bar {
			get {
				object obj = ResourceManager.GetObject ("chart_type_bar", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap chart_type_bar_percent {
			get {
				object obj = ResourceManager.GetObject ("chart_type_bar_percent", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap chart_type_bar_stack {
			get {
				object obj = ResourceManager.GetObject ("chart_type_bar_stack", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap chart_type_column {
			get {
				object obj = ResourceManager.GetObject ("chart_type_column", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap chart_type_column_percent {
			get {
				object obj = ResourceManager.GetObject ("chart_type_column_percent", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap chart_type_column_stack {
			get {
				object obj = ResourceManager.GetObject ("chart_type_column_stack", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap chart_type_donut {
			get {
				object obj = ResourceManager.GetObject ("chart_type_donut", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap chart_type_pie {
			get {
				object obj = ResourceManager.GetObject ("chart_type_pie", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap chart_type_polar {
			get {
				object obj = ResourceManager.GetObject ("chart_type_polar", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap chart_type_radar {
			get {
				object obj = ResourceManager.GetObject ("chart_type_radar", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap chartIco {
			get {
				object obj = ResourceManager.GetObject ("chartIco", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找类似 外观配置 的本地化字符串。
		/// </summary>
		internal static string context0001 {
			get {
				return ResourceManager.GetString ("context0001", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 区域管理 的本地化字符串。
		/// </summary>
		internal static string context0002 {
			get {
				return ResourceManager.GetString ("context0002", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 新增区域 的本地化字符串。
		/// </summary>
		internal static string context0003 {
			get {
				return ResourceManager.GetString ("context0003", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 删除区域 的本地化字符串。
		/// </summary>
		internal static string context0004 {
			get {
				return ResourceManager.GetString ("context0004", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 新增曲线 的本地化字符串。
		/// </summary>
		internal static string context0005 {
			get {
				return ResourceManager.GetString ("context0005", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 新增图例 的本地化字符串。
		/// </summary>
		internal static string context0006 {
			get {
				return ResourceManager.GetString ("context0006", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 新增标题 的本地化字符串。
		/// </summary>
		internal static string context0007 {
			get {
				return ResourceManager.GetString ("context0007", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 统计基准 的本地化字符串。
		/// </summary>
		internal static string context0008 {
			get {
				return ResourceManager.GetString ("context0008", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 统计字段 的本地化字符串。
		/// </summary>
		internal static string context0009 {
			get {
				return ResourceManager.GetString ("context0009", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 新增字段 的本地化字符串。
		/// </summary>
		internal static string context0010 {
			get {
				return ResourceManager.GetString ("context0010", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 删除字段 的本地化字符串。
		/// </summary>
		internal static string context0011 {
			get {
				return ResourceManager.GetString ("context0011", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 删除图例 的本地化字符串。
		/// </summary>
		internal static string context0012 {
			get {
				return ResourceManager.GetString ("context0012", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 删除标题 的本地化字符串。
		/// </summary>
		internal static string context0013 {
			get {
				return ResourceManager.GetString ("context0013", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 X轴 的本地化字符串。
		/// </summary>
		internal static string context0014 {
			get {
				return ResourceManager.GetString ("context0014", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 Y轴 的本地化字符串。
		/// </summary>
		internal static string context0015 {
			get {
				return ResourceManager.GetString ("context0015", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 曲线 的本地化字符串。
		/// </summary>
		internal static string context0016 {
			get {
				return ResourceManager.GetString ("context0016", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 添加曲线 的本地化字符串。
		/// </summary>
		internal static string context0017 {
			get {
				return ResourceManager.GetString ("context0017", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 删除曲线 的本地化字符串。
		/// </summary>
		internal static string context0018 {
			get {
				return ResourceManager.GetString ("context0018", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 添加Y轴 的本地化字符串。
		/// </summary>
		internal static string context0019 {
			get {
				return ResourceManager.GetString ("context0019", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 删除Y轴 的本地化字符串。
		/// </summary>
		internal static string context0020 {
			get {
				return ResourceManager.GetString ("context0020", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 配置数据源 的本地化字符串。
		/// </summary>
		internal static string context0021 {
			get {
				return ResourceManager.GetString ("context0021", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 配置外观 的本地化字符串。
		/// </summary>
		internal static string context0022 {
			get {
				return ResourceManager.GetString ("context0022", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 区域 的本地化字符串。
		/// </summary>
		internal static string context0023 {
			get {
				return ResourceManager.GetString ("context0023", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 图例 的本地化字符串。
		/// </summary>
		internal static string context0024 {
			get {
				return ResourceManager.GetString ("context0024", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 标题 的本地化字符串。
		/// </summary>
		internal static string context0025 {
			get {
				return ResourceManager.GetString ("context0025", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 特征标签 的本地化字符串。
		/// </summary>
		internal static string context0026 {
			get {
				return ResourceManager.GetString ("context0026", resourceCulture);
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap Data {
			get {
				object obj = ResourceManager.GetObject ("Data", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap flipvertical {
			get {
				object obj = ResourceManager.GetObject ("flipvertical", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   查找类似 至少要保留一个区域 的本地化字符串。
		/// </summary>
		internal static string message0001 {
			get {
				return ResourceManager.GetString ("message0001", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 此名称已被同类型占用,请重命名 的本地化字符串。
		/// </summary>
		internal static string message0002 {
			get {
				return ResourceManager.GetString ("message0002", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 至少要保留一个Y轴 的本地化字符串。
		/// </summary>
		internal static string message0003 {
			get {
				return ResourceManager.GetString ("message0003", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 请先指定一个数据源 的本地化字符串。
		/// </summary>
		internal static string message0004 {
			get {
				return ResourceManager.GetString ("message0004", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 曲线没有绑定Y轴或者字段 的本地化字符串。
		/// </summary>
		internal static string message0005 {
			get {
				return ResourceManager.GetString ("message0005", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 根据数据流重新构造控件失败 的本地化字符串。
		/// </summary>
		internal static string message0006 {
			get {
				return ResourceManager.GetString ("message0006", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 轴间距必须为正数 的本地化字符串。
		/// </summary>
		internal static string message0007 {
			get {
				return ResourceManager.GetString ("message0007", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 Y轴过多以致曲线无法显示 的本地化字符串。
		/// </summary>
		internal static string message0008 {
			get {
				return ResourceManager.GetString ("message0008", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 请指定特殊标签的数据源 的本地化字符串。
		/// </summary>
		internal static string message0009 {
			get {
				return ResourceManager.GetString ("message0009", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 特殊标签的标准字段必须为日期型 的本地化字符串。
		/// </summary>
		internal static string message0010 {
			get {
				return ResourceManager.GetString ("message0010", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 必须指定一个标准字段 的本地化字符串。
		/// </summary>
		internal static string message0011 {
			get {
				return ResourceManager.GetString ("message0011", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 标准字段有且只有一个 的本地化字符串。
		/// </summary>
		internal static string message0012 {
			get {
				return ResourceManager.GetString ("message0012", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 特征标签处理异常: 的本地化字符串。
		/// </summary>
		internal static string message0013 {
			get {
				return ResourceManager.GetString ("message0013", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 特征标签无法显示:标签主字段非时间类型 的本地化字符串。
		/// </summary>
		internal static string message0014 {
			get {
				return ResourceManager.GetString ("message0014", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 特征标签无法显示:无法找到标签字段内容 的本地化字符串。
		/// </summary>
		internal static string message0015 {
			get {
				return ResourceManager.GetString ("message0015", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 曲线没有绑定字段 的本地化字符串。
		/// </summary>
		internal static string message0016 {
			get {
				return ResourceManager.GetString ("message0016", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 数据不包含绑定字段 的本地化字符串。
		/// </summary>
		internal static string message0017 {
			get {
				return ResourceManager.GetString ("message0017", resourceCulture);
			}
		}

		/// <summary>
		///   查找类似 分段曲线的点的个数要为正整数 的本地化字符串。
		/// </summary>
		internal static string message0018 {
			get {
				return ResourceManager.GetString ("message0018", resourceCulture);
			}
		}

		/// <summary>
		///   查找 System.Drawing.Bitmap 类型的本地化资源。
		/// </summary>
		internal static System.Drawing.Bitmap OPEN {
			get {
				object obj = ResourceManager.GetObject ("OPEN", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
