// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PMS.Libraries.ToolControls.PMSPublicInfo {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PMSPublicResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMSPublicResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PMS.Libraries.ToolControls.PMSPublicInfo.PMSPublicResource", typeof(PMSPublicResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static string PMSDBAnalyseNavigateBarControl_DelAllReportAffirm {
            get {
                return ResourceManager.GetString("PMSDBAnalyseNavigateBarControl_DelAllReportAffirm", resourceCulture);
            }
        }
        
        public static string PMSDBAnalyseNavigateBarControl_DelReportAffirm {
            get {
                return ResourceManager.GetString("PMSDBAnalyseNavigateBarControl_DelReportAffirm", resourceCulture);
            }
        }
        
        public static string PMSDBAnalyseNavigateBarControl_DelReportGroupAffirm {
            get {
                return ResourceManager.GetString("PMSDBAnalyseNavigateBarControl_DelReportGroupAffirm", resourceCulture);
            }
        }
        
        public static string PMSDBAnalyseNavigateBarControl_NewReport {
            get {
                return ResourceManager.GetString("PMSDBAnalyseNavigateBarControl_NewReport", resourceCulture);
            }
        }
        
        public static string PMSDBAnalyseNavigateBarControl_ReportName {
            get {
                return ResourceManager.GetString("PMSDBAnalyseNavigateBarControl_ReportName", resourceCulture);
            }
        }
        
        public static string PMSDBConnectCtrl_DBConTestFail {
            get {
                return ResourceManager.GetString("PMSDBConnectCtrl_DBConTestFail", resourceCulture);
            }
        }
        
        public static string PMSDBConnectCtrl_DBConTestSucceed {
            get {
                return ResourceManager.GetString("PMSDBConnectCtrl_DBConTestSucceed", resourceCulture);
            }
        }
        
        public static string PMSDBConnectCtrl_DBServerNameIsNull {
            get {
                return ResourceManager.GetString("PMSDBConnectCtrl_DBServerNameIsNull", resourceCulture);
            }
        }
        
        public static string PMSDBConnectCtrl_RetrievingDataSources {
            get {
                return ResourceManager.GetString("PMSDBConnectCtrl_RetrievingDataSources", resourceCulture);
            }
        }
        
        public static string PMSDBDBNameNULL {
            get {
                return ResourceManager.GetString("PMSDBDBNameNULL", resourceCulture);
            }
        }
        
        public static string PMSDBServerNULL {
            get {
                return ResourceManager.GetString("PMSDBServerNULL", resourceCulture);
            }
        }
        
        public static string PMSDBUserIDNULL {
            get {
                return ResourceManager.GetString("PMSDBUserIDNULL", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_DocumentOutlineForm {
            get {
                return ResourceManager.GetString("PMSDVCtrl_DocumentOutlineForm", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_ErrorList {
            get {
                return ResourceManager.GetString("PMSDVCtrl_ErrorList", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_LogForm {
            get {
                return ResourceManager.GetString("PMSDVCtrl_LogForm", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_NavagateBar {
            get {
                return ResourceManager.GetString("PMSDVCtrl_NavagateBar", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_OutputForm {
            get {
                return ResourceManager.GetString("PMSDVCtrl_OutputForm", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_ProjectExplorer {
            get {
                return ResourceManager.GetString("PMSDVCtrl_ProjectExplorer", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_PropertyGridForm {
            get {
                return ResourceManager.GetString("PMSDVCtrl_PropertyGridForm", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_ToolBoxForm {
            get {
                return ResourceManager.GetString("PMSDVCtrl_ToolBoxForm", resourceCulture);
            }
        }
        
        public static string PMSFile_Copy {
            get {
                return ResourceManager.GetString("PMSFile_Copy", resourceCulture);
            }
        }
        
        public static string PMSGlobalClass_FileExisted {
            get {
                return ResourceManager.GetString("PMSGlobalClass_FileExisted", resourceCulture);
            }
        }
        
        public static string PMSGlobalClass_TableExisted {
            get {
                return ResourceManager.GetString("PMSGlobalClass_TableExisted", resourceCulture);
            }
        }
        
        public static string PMSLogForm_ErrorsFormat {
            get {
                return ResourceManager.GetString("PMSLogForm_ErrorsFormat", resourceCulture);
            }
        }
        
        public static string PMSLogForm_InfoFormat {
            get {
                return ResourceManager.GetString("PMSLogForm_InfoFormat", resourceCulture);
            }
        }
        
        public static string PMSLogForm_WarningFormat {
            get {
                return ResourceManager.GetString("PMSLogForm_WarningFormat", resourceCulture);
            }
        }
        
        public static string PMSLoginUserNULL {
            get {
                return ResourceManager.GetString("PMSLoginUserNULL", resourceCulture);
            }
        }
        
        public static string PMSNavigateBarControl_DelGroupAffirm {
            get {
                return ResourceManager.GetString("PMSNavigateBarControl_DelGroupAffirm", resourceCulture);
            }
        }
        
        public static string PMSNavigateBarControl_DelGroupViewsAffirm {
            get {
                return ResourceManager.GetString("PMSNavigateBarControl_DelGroupViewsAffirm", resourceCulture);
            }
        }
        
        public static string PMSNavigateBarControl_GroupName {
            get {
                return ResourceManager.GetString("PMSNavigateBarControl_GroupName", resourceCulture);
            }
        }
        
        public static string PMSNavigateBarControl_GroupNameCantNull {
            get {
                return ResourceManager.GetString("PMSNavigateBarControl_GroupNameCantNull", resourceCulture);
            }
        }
        
        public static string PMSNavigateBarControl_NewGroup {
            get {
                return ResourceManager.GetString("PMSNavigateBarControl_NewGroup", resourceCulture);
            }
        }
        
        public static string PMSNavigateBarControl_RefreshAllAffirm {
            get {
                return ResourceManager.GetString("PMSNavigateBarControl_RefreshAllAffirm", resourceCulture);
            }
        }
        
        public static string PMSNewOrgStructTable_TableNameCantNull {
            get {
                return ResourceManager.GetString("PMSNewOrgStructTable_TableNameCantNull", resourceCulture);
            }
        }
        
        public static string PMSOrgNavigateBarControl_DelAllOrgAffirm {
            get {
                return ResourceManager.GetString("PMSOrgNavigateBarControl_DelAllOrgAffirm", resourceCulture);
            }
        }
        
        public static string PMSOrgNavigateBarControl_DelOrgAffirm {
            get {
                return ResourceManager.GetString("PMSOrgNavigateBarControl_DelOrgAffirm", resourceCulture);
            }
        }
        
        public static string PMSOrgNavigateBarControl_DelOrgGroupAffirm {
            get {
                return ResourceManager.GetString("PMSOrgNavigateBarControl_DelOrgGroupAffirm", resourceCulture);
            }
        }
        
        public static string PMSOrgNavigateBarControl_NewOrg {
            get {
                return ResourceManager.GetString("PMSOrgNavigateBarControl_NewOrg", resourceCulture);
            }
        }
        
        public static string PMSOrgNavigateBarControl_OrgName {
            get {
                return ResourceManager.GetString("PMSOrgNavigateBarControl_OrgName", resourceCulture);
            }
        }
        
        public static string PMSSheetDesignerNavigateBarControl_DelAllSheetAffirm {
            get {
                return ResourceManager.GetString("PMSSheetDesignerNavigateBarControl_DelAllSheetAffirm", resourceCulture);
            }
        }
        
        public static string PMSSheetDesignerNavigateBarControl_DelSheetAffirm {
            get {
                return ResourceManager.GetString("PMSSheetDesignerNavigateBarControl_DelSheetAffirm", resourceCulture);
            }
        }
        
        public static string PMSSheetDesignerNavigateBarControl_DelSheetGroupAffirm {
            get {
                return ResourceManager.GetString("PMSSheetDesignerNavigateBarControl_DelSheetGroupAffirm", resourceCulture);
            }
        }
        
        public static string PMSSheetDesignerNavigateBarControl_NewSheet {
            get {
                return ResourceManager.GetString("PMSSheetDesignerNavigateBarControl_NewSheet", resourceCulture);
            }
        }
        
        public static string PMSSheetDesignerNavigateBarControl_SheetName {
            get {
                return ResourceManager.GetString("PMSSheetDesignerNavigateBarControl_SheetName", resourceCulture);
            }
        }
        
        public static string PMSSqlAssistance_DBNULL {
            get {
                return ResourceManager.GetString("PMSSqlAssistance_DBNULL", resourceCulture);
            }
        }
        
        public static string PMSTemplateNavigateBarControl_DelAllTemplateAffirm {
            get {
                return ResourceManager.GetString("PMSTemplateNavigateBarControl_DelAllTemplateAffirm", resourceCulture);
            }
        }
        
        public static string PMSTemplateNavigateBarControl_DelTemplateAffirm {
            get {
                return ResourceManager.GetString("PMSTemplateNavigateBarControl_DelTemplateAffirm", resourceCulture);
            }
        }
        
        public static string PMSTemplateNavigateBarControl_DelUserTemplateAffirm {
            get {
                return ResourceManager.GetString("PMSTemplateNavigateBarControl_DelUserTemplateAffirm", resourceCulture);
            }
        }
        
        public static string PMSTemplateNavigateBarControl_NewTemplate {
            get {
                return ResourceManager.GetString("PMSTemplateNavigateBarControl_NewTemplate", resourceCulture);
            }
        }
        
        public static string PMSTemplateNavigateBarControl_TemplateName {
            get {
                return ResourceManager.GetString("PMSTemplateNavigateBarControl_TemplateName", resourceCulture);
            }
        }
        
        public static string PMSUserCustomNavigateBarControl_DelAllUserCustomAffirm {
            get {
                return ResourceManager.GetString("PMSUserCustomNavigateBarControl_DelAllUserCustomAffirm", resourceCulture);
            }
        }
        
        public static string PMSUserCustomNavigateBarControl_DelUserCustomAffirm {
            get {
                return ResourceManager.GetString("PMSUserCustomNavigateBarControl_DelUserCustomAffirm", resourceCulture);
            }
        }
        
        public static string PMSUserCustomNavigateBarControl_DelUserCustomGroupAffirm {
            get {
                return ResourceManager.GetString("PMSUserCustomNavigateBarControl_DelUserCustomGroupAffirm", resourceCulture);
            }
        }
        
        public static string PMSUserCustomNavigateBarControl_NewUserCustom {
            get {
                return ResourceManager.GetString("PMSUserCustomNavigateBarControl_NewUserCustom", resourceCulture);
            }
        }
        
        public static string PMSUserCustomNavigateBarControl_UserCustomName {
            get {
                return ResourceManager.GetString("PMSUserCustomNavigateBarControl_UserCustomName", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_AllVersionHasDeletedByOther {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_AllVersionHasDeletedByOther", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_DelAllViewVersions {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_DelAllViewVersions", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_DelCurrentActiveView {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_DelCurrentActiveView", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_DelView {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_DelView", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_FormatTabText {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_FormatTabText", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_FormatTabToolTipText {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_FormatTabToolTipText", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_HasCheckOutByOther {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_HasCheckOutByOther", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_HasCheckOutByOthersStopOrContinue {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_HasCheckOutByOthersStopOrContinue", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_HasDeletedByOther {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_HasDeletedByOther", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_OpenViewAsync {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_OpenViewAsync", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_OtherUserConfiging {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_OtherUserConfiging", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_RefreshFromDBTip {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_RefreshFromDBTip", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_RunViewAsync {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_RunViewAsync", resourceCulture);
            }
        }
        
        public static string PMS_ConnectError {
            get {
                return ResourceManager.GetString("PMS_ConnectError", resourceCulture);
            }
        }
        
        public static string PMS_CoverOrNew {
            get {
                return ResourceManager.GetString("PMS_CoverOrNew", resourceCulture);
            }
        }
        
        public static string PMS_DBDesigner {
            get {
                return ResourceManager.GetString("PMS_DBDesigner", resourceCulture);
            }
        }
        
        public static string PMS_Edit {
            get {
                return ResourceManager.GetString("PMS_Edit", resourceCulture);
            }
        }
        
        public static string PMS_Error {
            get {
                return ResourceManager.GetString("PMS_Error", resourceCulture);
            }
        }
        
        public static string PMS_Fail {
            get {
                return ResourceManager.GetString("PMS_Fail", resourceCulture);
            }
        }
        
        public static string PMS_IsExpanding {
            get {
                return ResourceManager.GetString("PMS_IsExpanding", resourceCulture);
            }
        }
        
        public static string PMS_Msg {
            get {
                return ResourceManager.GetString("PMS_Msg", resourceCulture);
            }
        }
        
        public static string PMS_NotExisted {
            get {
                return ResourceManager.GetString("PMS_NotExisted", resourceCulture);
            }
        }
        
        public static string PMS_OrgnizationStruct {
            get {
                return ResourceManager.GetString("PMS_OrgnizationStruct", resourceCulture);
            }
        }
        
        public static string PMS_Report {
            get {
                return ResourceManager.GetString("PMS_Report", resourceCulture);
            }
        }
        
        public static string PMS_Runtime {
            get {
                return ResourceManager.GetString("PMS_Runtime", resourceCulture);
            }
        }
        
        public static string PMS_Sheet {
            get {
                return ResourceManager.GetString("PMS_Sheet", resourceCulture);
            }
        }
        
        public static string PMS_Static {
            get {
                return ResourceManager.GetString("PMS_Static", resourceCulture);
            }
        }
        
        public static string PMS_Succeed {
            get {
                return ResourceManager.GetString("PMS_Succeed", resourceCulture);
            }
        }
        
        public static string PMS_TestRunTime {
            get {
                return ResourceManager.GetString("PMS_TestRunTime", resourceCulture);
            }
        }
        
        public static string PMS_UserCustom {
            get {
                return ResourceManager.GetString("PMS_UserCustom", resourceCulture);
            }
        }
        
        public static string PMS_Warnning {
            get {
                return ResourceManager.GetString("PMS_Warnning", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap skin {
            get {
                object obj = ResourceManager.GetObject("skin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static string PMSDBAccessPathNULL {
            get {
                return ResourceManager.GetString("PMSDBAccessPathNULL", resourceCulture);
            }
        }
        
        public static string DBStructAnalyseNavigateBarControl_Tables {
            get {
                return ResourceManager.GetString("DBStructAnalyseNavigateBarControl_Tables", resourceCulture);
            }
        }
        
        public static string DBStructAnalyseNavigateBarControl_Views {
            get {
                return ResourceManager.GetString("DBStructAnalyseNavigateBarControl_Views", resourceCulture);
            }
        }
        
        public static string PMSNavigateBarControl_LoadAs {
            get {
                return ResourceManager.GetString("PMSNavigateBarControl_LoadAs", resourceCulture);
            }
        }
        
        public static string PMS_FileError {
            get {
                return ResourceManager.GetString("PMS_FileError", resourceCulture);
            }
        }
        
        public static string PMS_DBVersionNotMatch {
            get {
                return ResourceManager.GetString("PMS_DBVersionNotMatch", resourceCulture);
            }
        }
        
        public static string PMS_DBVersionLower {
            get {
                return ResourceManager.GetString("PMS_DBVersionLower", resourceCulture);
            }
        }
        
        public static string PMS_CannotBeNull {
            get {
                return ResourceManager.GetString("PMS_CannotBeNull", resourceCulture);
            }
        }
        
        public static string PMSClient_Login {
            get {
                return ResourceManager.GetString("PMSClient_Login", resourceCulture);
            }
        }
        
        public static string PMSClient_Logout {
            get {
                return ResourceManager.GetString("PMSClient_Logout", resourceCulture);
            }
        }
        
        public static string PMSDEV_Login {
            get {
                return ResourceManager.GetString("PMSDEV_Login", resourceCulture);
            }
        }
        
        public static string PMSDEV_Logout {
            get {
                return ResourceManager.GetString("PMSDEV_Logout", resourceCulture);
            }
        }
        
        public static string PMSDBStructLoading {
            get {
                return ResourceManager.GetString("PMSDBStructLoading", resourceCulture);
            }
        }
        
        public static string PMSLoadTip {
            get {
                return ResourceManager.GetString("PMSLoadTip", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_MoveWhenInsertSameNamedView {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_MoveWhenInsertSameNamedView", resourceCulture);
            }
        }
        
        public static string PMS_Tip {
            get {
                return ResourceManager.GetString("PMS_Tip", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_ViewPowerGroupConfig {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_ViewPowerGroupConfig", resourceCulture);
            }
        }
        
        public static string PMSViewNameCantNull {
            get {
                return ResourceManager.GetString("PMSViewNameCantNull", resourceCulture);
            }
        }
        
        public static string PMS_Rename {
            get {
                return ResourceManager.GetString("PMS_Rename", resourceCulture);
            }
        }
        
        public static string PMS_ReportDesigner {
            get {
                return ResourceManager.GetString("PMS_ReportDesigner", resourceCulture);
            }
        }
        
        public static string PMS_DBTableDesigner {
            get {
                return ResourceManager.GetString("PMS_DBTableDesigner", resourceCulture);
            }
        }
        
        public static string PMSDBDesignerNavigateBarControl_ColumnProtected {
            get {
                return ResourceManager.GetString("PMSDBDesignerNavigateBarControl_ColumnProtected", resourceCulture);
            }
        }
        
        public static string PMSDBDesignerNavigateBarControl_DelTable {
            get {
                return ResourceManager.GetString("PMSDBDesignerNavigateBarControl_DelTable", resourceCulture);
            }
        }
        
        public static string PMSDBDesignerNavigateBarControl_DelTableColumn {
            get {
                return ResourceManager.GetString("PMSDBDesignerNavigateBarControl_DelTableColumn", resourceCulture);
            }
        }
        
        public static string PMSDBDesignerControl_CheckValidateNeedColumnName {
            get {
                return ResourceManager.GetString("PMSDBDesignerControl_CheckValidateNeedColumnName", resourceCulture);
            }
        }
        
        public static string PMSDBDesignerControl_CheckValidateNeedColumnType {
            get {
                return ResourceManager.GetString("PMSDBDesignerControl_CheckValidateNeedColumnType", resourceCulture);
            }
        }
        
        public static string PMSDBTableRelationConfig {
            get {
                return ResourceManager.GetString("PMSDBTableRelationConfig", resourceCulture);
            }
        }
        
        public static string PMS_DBTableRecord {
            get {
                return ResourceManager.GetString("PMS_DBTableRecord", resourceCulture);
            }
        }
        
        public static string NewDBSourceForm_DBSourceCantNull {
            get {
                return ResourceManager.GetString("NewDBSourceForm_DBSourceCantNull", resourceCulture);
            }
        }
        
        public static string NewDBSourceForm_DBSourceExisted {
            get {
                return ResourceManager.GetString("NewDBSourceForm_DBSourceExisted", resourceCulture);
            }
        }
        
        public static string DBRefConnectionSelectForm_NoSelectDBSource {
            get {
                return ResourceManager.GetString("DBRefConnectionSelectForm_NoSelectDBSource", resourceCulture);
            }
        }
        
        public static string PMSDBOraclePortIDNULL {
            get {
                return ResourceManager.GetString("PMSDBOraclePortIDNULL", resourceCulture);
            }
        }
        
        public static string PMSDBOracleSIDNULL {
            get {
                return ResourceManager.GetString("PMSDBOracleSIDNULL", resourceCulture);
            }
        }
        
        public static string MES_SheetDesigner {
            get {
                return ResourceManager.GetString("MES_SheetDesigner", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_SourceConfigToolWindow {
            get {
                return ResourceManager.GetString("PMSDVCtrl_SourceConfigToolWindow", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_DataSourceToolWindow {
            get {
                return ResourceManager.GetString("PMSDVCtrl_DataSourceToolWindow", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_NodeTemplateWindow {
            get {
                return ResourceManager.GetString("PMSDVCtrl_NodeTemplateWindow", resourceCulture);
            }
        }
        
        public static string MESControlProperty {
            get {
                return ResourceManager.GetString("MESControlProperty", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_WorkFlowManagerForm {
            get {
                return ResourceManager.GetString("PMSDVCtrl_WorkFlowManagerForm", resourceCulture);
            }
        }
        
        public static string PMS_WorkFlowDesign {
            get {
                return ResourceManager.GetString("PMS_WorkFlowDesign", resourceCulture);
            }
        }
        
        public static string PMS_WorkFlowMonitor {
            get {
                return ResourceManager.GetString("PMS_WorkFlowMonitor", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_WorkFlowMonitoringForm {
            get {
                return ResourceManager.GetString("PMSDVCtrl_WorkFlowMonitoringForm", resourceCulture);
            }
        }
        
        public static string MESBusinessTableGenerateForm_NoField {
            get {
                return ResourceManager.GetString("MESBusinessTableGenerateForm_NoField", resourceCulture);
            }
        }
        
        public static string MESBusinessTableGenerateForm_TableGenerated {
            get {
                return ResourceManager.GetString("MESBusinessTableGenerateForm_TableGenerated", resourceCulture);
            }
        }
        
        public static string MESBusinessTableGenerateForm_TableGenerating {
            get {
                return ResourceManager.GetString("MESBusinessTableGenerateForm_TableGenerating", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_ClipboardForm {
            get {
                return ResourceManager.GetString("PMSDVCtrl_ClipboardForm", resourceCulture);
            }
        }
        
        public static string PMS_WorkFlowINstanceMonitor {
            get {
                return ResourceManager.GetString("PMS_WorkFlowINstanceMonitor", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_WorkFlowCustomForm {
            get {
                return ResourceManager.GetString("PMSDVCtrl_WorkFlowCustomForm", resourceCulture);
            }
        }
        
        public static string PMS_WorkFlowCustomDesign {
            get {
                return ResourceManager.GetString("PMS_WorkFlowCustomDesign", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_DBStructAnalyseForm {
            get {
                return ResourceManager.GetString("PMSDVCtrl_DBStructAnalyseForm", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_WorkFlowProcessList {
            get {
                return ResourceManager.GetString("PMSDVCtrl_WorkFlowProcessList", resourceCulture);
            }
        }
        
        public static string MES_RefDBNotFound {
            get {
                return ResourceManager.GetString("MES_RefDBNotFound", resourceCulture);
            }
        }
        
        public static string PMSUserCustomNavigateBarControl_CheckInSucceed {
            get {
                return ResourceManager.GetString("PMSUserCustomNavigateBarControl_CheckInSucceed", resourceCulture);
            }
        }
        
        public static System.Windows.Forms.ImageListStreamer imageList1_ImageStream {
            get {
                object obj = ResourceManager.GetObject("imageList1.ImageStream", resourceCulture);
                return ((System.Windows.Forms.ImageListStreamer)(obj));
            }
        }
        
        public static string MESPleaseSelectForm {
            get {
                return ResourceManager.GetString("MESPleaseSelectForm", resourceCulture);
            }
        }
        
        public static string MESPleaseSelectReport {
            get {
                return ResourceManager.GetString("MESPleaseSelectReport", resourceCulture);
            }
        }
        
        public static string MESPleaseSelectView {
            get {
                return ResourceManager.GetString("MESPleaseSelectView", resourceCulture);
            }
        }
        
        public static string MESNavigatorDesigner {
            get {
                return ResourceManager.GetString("MESNavigatorDesigner", resourceCulture);
            }
        }
        
        public static string MES_ExitSystem {
            get {
                return ResourceManager.GetString("MES_ExitSystem", resourceCulture);
            }
        }
        
        public static string PMSDBConnectCtrl_UserLoginFail {
            get {
                return ResourceManager.GetString("PMSDBConnectCtrl_UserLoginFail", resourceCulture);
            }
        }
        
        public static string MES_UpdateRefDBFileToServerFail {
            get {
                return ResourceManager.GetString("MES_UpdateRefDBFileToServerFail", resourceCulture);
            }
        }
        
        public static string MESCantFindWFWaitTaskForm {
            get {
                return ResourceManager.GetString("MESCantFindWFWaitTaskForm", resourceCulture);
            }
        }
        
        public static string MES_LogOut {
            get {
                return ResourceManager.GetString("MES_LogOut", resourceCulture);
            }
        }
        
        public static string PMSOleDBConnectStringNull {
            get {
                return ResourceManager.GetString("PMSOleDBConnectStringNull", resourceCulture);
            }
        }
        
        public static string MESReportIsNotAuthorized {
            get {
                return ResourceManager.GetString("MESReportIsNotAuthorized", resourceCulture);
            }
        }
        
        public static string DBStructAnalyseNavigateBarControl_StoredProcedures {
            get {
                return ResourceManager.GetString("DBStructAnalyseNavigateBarControl_StoredProcedures", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_WorkFlowDesign {
            get {
                return ResourceManager.GetString("PMSDVCtrl_WorkFlowDesign", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_WorkFlowRun {
            get {
                return ResourceManager.GetString("PMSDVCtrl_WorkFlowRun", resourceCulture);
            }
        }
        
        public static string MESUserHasLogin {
            get {
                return ResourceManager.GetString("MESUserHasLogin", resourceCulture);
            }
        }
        
        public static string MESUserIDDuplicate {
            get {
                return ResourceManager.GetString("MESUserIDDuplicate", resourceCulture);
            }
        }
        
        public static string MESUserIDIsNotEnable {
            get {
                return ResourceManager.GetString("MESUserIDIsNotEnable", resourceCulture);
            }
        }
        
        public static string MESUserIDNotExist {
            get {
                return ResourceManager.GetString("MESUserIDNotExist", resourceCulture);
            }
        }
        
        public static string MESUserPswError {
            get {
                return ResourceManager.GetString("MESUserPswError", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_RuntimeFormatTabToolTipText {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_RuntimeFormatTabToolTipText", resourceCulture);
            }
        }
        
        public static string PMSUserViewNavigateBarControl_TemplateFormatTabToolTipText {
            get {
                return ResourceManager.GetString("PMSUserViewNavigateBarControl_TemplateFormatTabToolTipText", resourceCulture);
            }
        }
        
        public static string PMSDVCtrl_SystemConfig {
            get {
                return ResourceManager.GetString("PMSDVCtrl_SystemConfig", resourceCulture);
            }
        }
        
        public static string MESPublishToServerAsync {
            get {
                return ResourceManager.GetString("MESPublishToServerAsync", resourceCulture);
            }
        }
        
        public static string NotCheckOutReadOnlyWarning {
            get {
                return ResourceManager.GetString("NotCheckOutReadOnlyWarning", resourceCulture);
            }
        }
        
        public static string PMSGlobalClass_GroupExisted {
            get {
                return ResourceManager.GetString("PMSGlobalClass_GroupExisted", resourceCulture);
            }
        }
    }
}
